/* LOGIN OR REGISTER */
export const USER_LOGIN_OR_SIGNUP = 'USER_LOGIN_OR_SIGNUP';
export const USER_LOGIN_OR_SIGNUP_ERROR = 'USER_LOGIN_OR_SIGNUP_ERROR';
export const USER_LOGIN_OR_SIGNUP_LOADING = 'USER_LOGIN_OR_SIGNUP_LOADING';

/* ALL USER LIST */
export const ALL_USER_LIST = 'ALL_USER_LIST';
export const ALL_USER_LIST_ERRROR = 'ALL_USER_LIST_ERRROR';
export const ALL_USER_LIST_LOADING = 'ALL_USER_LIST_LOADING';

/* CREATE GROUP */
export const CREATE_GROOUP_SUCCESS = 'CREATE_GROOUP_SUCCESS';
export const CREATE_GROOUP_ERROR = 'CREATE_GROOUP_ERROR';
export const CREATE_GROOUP_LOADING = 'CREATE_GROOUP_LOADING';

/* CREATE GROUP */
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_ERROR = 'CREATE_ROOM_ERROR';
export const CREATE_ROOM_LOADING = 'CREATE_ROOM_LOADING';

/* GROUP LIST */
export const ALL_ROOMS_DATA = 'ALL_ROOMS_DATA';
export const ALL_GROUP_LIST = 'ALL_GROUP_LIST';
export const ALL_GROUP_LIST_ERRROR = 'ALL_GROUP_LIST_ERRROR';
export const ALL_GROUP_LIST_SUCCESS = 'ALL_GROUP_LIST_SUCCESS';

export const ROOM_MODIFIED_WITH_MESSAGE = 'ROOM_MODIFIED_WITH_MESSAGE';
export const MESSAGE_IN_ROOM = 'MESSAGE_IN_ROOM';
export const ALL_MESSAGE_IN_ROOM = 'ALL_MESSAGE_IN_ROOM';
export const CLEAR_ALL_MESSAGE_IN_ROOM = 'CLEAR_ALL_MESSAGE_IN_ROOM';
export const LOGGED_IN_USER = 'LOGGED_IN_USER';
export const CHAT_WITH_USER = 'CHAT_WITH_USER';


export const ALL_MESSAGES_LOADING = 'ALL_MESSAGES_LOADING';



export const USER_MODIFY = 'USER_MODIFY';
